version: '3.8'

services:
  
  watchlist:
    image: node:20
    working_dir: /app
    volumes:
      - ../../:/app
      - ../../node_modules:/app/node_modules
      - ../../dist:/app/dist
    command: bash -c "npm i --quiet --ignore-scripts && npm run start:dev"
    environment:
      - JWT_KEY=testingJdoubleuT
      - APP_PORT=3000
      - MONGO_URI=mongodb://root:root@mongodb:27017/watchlist?authSource=admin
    ports:
      - "3000:3000"
    networks:
      - app
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  mongodb_data:
    driver: local